version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    command: make run

  task_tracker:
    build: 
      context: ./task_tracker
      dockerfile: Dockerfile
    volumes:
      - ./task_tracker:/app
      - .env:/app/.env
    command: make run
  
  app:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run build"
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"  

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432